name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: 'stable' }
      - run: cd app && flutter pub get
      - run: cd app && flutter analyze && flutter test
      - run: |
          cd app
          flutter build appbundle --release \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL_STG }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY_STG }}