name: flutter-ci

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  analyze-and-build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Pub get
        working-directory: app
        run: flutter pub get

      - name: Format check
        working-directory: app
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        working-directory: app
        run: flutter analyze --no-pub

      - name: Test
        working-directory: app
        run: flutter test --platform=chrome --headless || flutter test

      - name: Build Web (release)
        working-directory: app
        run: flutter build web --release --web-renderer html

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: app/build/web
